### ISSUE TITLE
只想要 api 封装的那部分怎么用

### ISSUE THREAD

**Issue by xiaomizhou66** [young-js/wx-promise-pro#28]

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/54997158-0d9e1300-5006-11e9-93ee-b1de14207cc9.png)

**Comment by youngjuning** [comment]
目前没有办法，不过没有挂载多少自定义的方法。如果真的想只用 api 的那部分，看下 源码，把自顶义的api删了就可以

**Comment by xiaomizhou66** [comment]
谢谢
